--- #YAML:1.0
name:               WWW-Mechanize-Plugin-AutoWrite
version:            0.06
abstract:           WWW::Mechanize plugin that writes the fetched pages to the disk.
author:
    - Jozef Kutej <jkutej@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               0
    Class::Accessor:    0
    File::Basename:     0
    File::Path:         0
    File::Slurp:        0
    File::Spec:         0
    File::Temp:         0
    MIME::Types:        0
    Scalar::Util:       0
    Test::Differences:  0
    Test::More:         0
    WWW::Mechanize:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
